version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"

  nodejs:
    build: .
    environment:
      DB_CONNECTION_STRING: "mysql+pymysql://root:password@mysql:3306/testdb"
    depends_on:
      - mysql
