name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    name: Build and Test Docker Image for Selected Branch
    runs-on: self-hosted

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      # Set branch name
      - name: Set branch name
        id: set-branch
        run: echo "BRANCH_NAME=${{ github.ref }}" | sed 's|refs/heads/||' >> $GITHUB_ENV

      # Install Node.js (Next.js needs Node.js environment)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies (if your Next.js app uses npm/yarn)
      - name: Install dependencies
        run: npm install  # Or use `yarn install` if you use Yarn

      # Build the Next.js app
      - name: Build Next.js app
        run: npm run build  # Or `yarn build` if you use Yarn

      # Build Docker image for Next.js
      - name: Build Docker image
        run: |
          docker build -t nextjs_app:${{ env.BRANCH_NAME }} .

      # Verify Docker images
      - name: Verify Docker images
        run: docker images

      # Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker tag nextjs_app:${{ env.BRANCH_NAME }} ${{ secrets.DOCKER_USERNAME }}/nextjs_app:${{ env.BRANCH_NAME }}
          docker push ${{ secrets.DOCKER_USERNAME }}/nextjs_app:${{ env.BRANCH_NAME }}

      # Run Docker container with Next.js app
      - name: Run Docker container
        run: |
          docker run --rm -d -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/nextjs_app:${{ env.BRANCH_NAME }}

      # Verify the container is running
      - name: Verify container is running
        run: |
          CONTAINER_ID=$(docker ps -q -f "ancestor=${{ secrets.DOCKER_USERNAME }}/nextjs_app:${{ env.BRANCH_NAME }}")
          docker logs --tail 100 -f $CONTAINER_ID & sleep 30; kill $!
