name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  docker-build:
   name: Build and Test Docker Image for Selected Branch
   runs-on: ubuntu-latest
   
   steps:
     # Checkout the repository 
     - name: Checkout code
       uses: actions/checkout@v3

     # Set up SSH for deployment (if needed for a local machine)
     - name: Set up SSH
       uses: webfactory/ssh-agent@v0.5.3
       with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

     # Set branch name
     - name: Set branch name
       id: set-branch
       run: echo "BRANCH_NAME=${{ github.ref }}" | sed 's|refs/heads/||' >> $GITHUB_ENV

     # Install Node.js and dependencies
     - name: Set up Node.js
       uses: actions/setup-node@v3
       with:
         node-version: '18'
         cache: 'npm'

     - name: Install dependencies
       run: npm install

     # Build the Next.js app
     - name: Build Next.js app
       run: npm run build

     # Install Docker on the GitHub runner
     - name: Install Docker
       run: |
         sudo apt-get update
         sudo apt-get install -y docker.io
         sudo usermod -aG docker $USER

     # Start Docker Desktop (optional step if using Docker Desktop on the CI runner)
     - name: Start Docker Desktop
       run: |
         sudo systemctl start docker
         sudo systemctl enable docker

     # Build Docker image using local Docker Desktop daemon
     - name: Build Docker image
       run: |
         docker build -t nextjs_app:${{ env.BRANCH_NAME }} .

     # Verify Docker images
     - name: Verify Docker images
       run: docker images

     # Deploy to Docker Desktop (local machine)
     - name: Deploy Docker container on Docker Desktop
       run: |
         docker run -d -p 3000:3000 nextjs_app:${{ env.BRANCH_NAME }}

     # Verify container is running on Docker Desktop
     - name: Verify container is running
       run: |
         CONTAINER_ID=$(docker ps -q -f "ancestor=nextjs_app:${{ env.BRANCH_NAME }}")
         docker logs --tail 100 -f $CONTAINER_ID & sleep 30; kill $!
